export const OVERLAY_COPY = {
  agentSelectLabel: 'Agent',
  agentSelectPlaceholder: 'Default agent',
  captureLabel: 'Take a screenshot',
  clearSelectionLabel: 'Clear selection',
  closeLabel: 'Close',
  composePlaceholder: 'Ask anything…',
  customRegionLabel: 'Custom region',
  hintDragRegion: 'Capture a region',
  hintDragTrigger: 'Drag',
  hintExit: 'Exit',
  hintHoverTrigger: 'Hover',
  hintSelectWindow: 'Select active window',
  idlePlaceholder: 'Select a window or drag a region to start asking…',
  latestSelectionLabel: 'Latest',
  modelSelectLabel: 'Model',
  modelSelectPlaceholder: 'Default model',
  multipleSelectedPlaceholder: 'Ask about these screenshots…',
  newlineHint: 'New line',
  removeSelectionLabel: 'Remove selection',
  screenshotLabel: 'Screenshot',
  screenshotsLabel: 'Screenshots',
  selectedPlaceholder: 'Ask about this screenshot…',
  selectionFormatLabel: 'PNG',
  sendAriaLabel: 'Send',
  sendHint: 'Send',
  uploadFailedLabel: 'Upload failed',
  uploadingLabel: 'Uploading screenshot…',
} as const;

export const OVERLAY_SHORTCUTS = {
  close: 'Esc',
  newline: 'Shift + Enter',
  send: 'Enter',
} as const;

export const OVERLAY_LAYOUT = {
  clickToDragThreshold: 5,
  connectorSize: 8,
  dockGap: 12,
  labelClipLength: 60,
  minDragSize: 10,
  panelBottomGap: 32,
  panelHeightEstimate: 208,
  panelHeightEstimateExpanded: 300,
  panelWidthDocked: 440,
  panelWidthInitial: 560,
  viewportMargin: 16,
  windowTagHorizontalInset: 12,
  windowTagMaxWidth: 420,
  windowTagTopOffset: 12,
} as const;
