import fs from 'node:fs';
import { builtinModules, createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'vite';

const desktopDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.join(desktopDir, 'package.json'));
const { version } = require('electron-updater/package.json');

const outFile = path.join(desktopDir, 'shell/rescue/electron-updater.cjs');

await build({
  build: {
    emptyOutDir: false,
    minify: true,
    outDir: path.join(desktopDir, 'shell/rescue'),
    rolldownOptions: {
      external: ['electron', ...builtinModules, ...builtinModules.map((m) => `node:${m}`)],
      output: {
        entryFileNames: 'electron-updater.cjs',
        format: 'cjs',
      },
    },
    ssr: require.resolve('electron-updater'),
    target: 'node22',
  },
  configFile: false,
  logLevel: 'warn',
  root: desktopDir,
  ssr: { noExternal: true },
});

fs.writeFileSync(
  outFile,
  `/* electron-updater@${version} generated by shell:vendor */\n${fs.readFileSync(outFile, 'utf8')}`,
);

console.log(`vendored electron-updater@${version} into shell/rescue/electron-updater.cjs`);
