name: E2E CI
permissions:
  contents: read

on:
    pull_request:
    push:

concurrency:
    group: e2e-${{ github.ref }}
    cancel-in-progress: true

jobs:
    e2e:
        name: Test Web App
        runs-on: ubuntu-latest
        timeout-minutes: 25
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.23

            - name: Install dependencies (bun)
              run: bun install

            - name: Install Playwright browsers (with system deps)
              run: bunx playwright install --with-deps chromium

            - name: Run E2E tests
              env:
                  PORT: 3010
              run: bun run e2e

            - name: Upload Cucumber HTML report (on failure)
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: cucumber-report
                  path: e2e/reports
                  if-no-files-found: ignore

            - name: Upload screenshots (on failure)
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: test-screenshots
                  path: e2e/screenshots
                  if-no-files-found: ignore
