name: "Lock Stale Issues"

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: lock-threads

jobs:
  lock-closed-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Lock closed issues after 7 days of inactivity
        uses: actions/github-script@v7
        with:
          script: |
            const lockScript = require('./.github/scripts/lock-closed-issues.js');
            await lockScript({ github, context });
