import { type AIChatModelCard } from '../types/aiModel';

// ref: https://opencode.ai/zen
// Model data sourced from models.dev API (opencode provider)

const opencodeZenChatModels: AIChatModelCard[] = [
  // ========== Anthropic Claude ==========
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 200_000,
    description:
      'Claude Haiku 3.5 by Anthropic — fast and cost-efficient model with vision support.',
    displayName: 'Claude Haiku 3.5',
    enabled: false,
    family: 'claude',
    generation: 'claude-3.5',
    id: 'claude-3-5-haiku',
    knowledgeCutoff: '2024-07',
    maxOutput: 8192,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.8, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.08, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 1, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2024-10-22',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 200_000,
    description:
      'Claude Haiku 4.5 by Anthropic — next-gen Haiku with enhanced reasoning and vision.',
    displayName: 'Claude Haiku 4.5',
    enabled: false,
    family: 'claude',
    generation: 'claude-4.5',
    id: 'claude-haiku-4-5',
    knowledgeCutoff: '2025-02',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.1, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 1.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-10-15',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 200_000,
    description:
      'Claude Opus 4.1 by Anthropic — premium reasoning model with deep analysis capabilities.',
    displayName: 'Claude Opus 4.1',
    enabled: false,
    family: 'claude',
    generation: 'claude-4.1',
    id: 'claude-opus-4-1',
    knowledgeCutoff: '2025-01',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 1.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 18.75, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-08-05',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 200_000,
    description:
      'Claude Opus 4.5 by Anthropic — flagship model with top-tier reasoning and coding.',
    displayName: 'Claude Opus 4.5',
    enabled: false,
    family: 'claude',
    generation: 'claude-4.5',
    id: 'claude-opus-4-5',
    knowledgeCutoff: '2025-05',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 6.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-11-24',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description:
      'Claude Opus 4.6 by Anthropic — 1M context window flagship with advanced reasoning.',
    displayName: 'Claude Opus 4.6',
    enabled: false,
    family: 'claude',
    generation: 'claude-4.6',
    id: 'claude-opus-4-6',
    knowledgeCutoff: '2025-05',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 6.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-05',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description:
      'Claude Opus 4.7 by Anthropic — latest Opus with state-of-the-art reasoning and coding.',
    displayName: 'Claude Opus 4.7',
    enabled: true,
    family: 'claude',
    generation: 'claude-4.7',
    id: 'claude-opus-4-7',
    knowledgeCutoff: '2026-01',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 6.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-04-16',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description:
      'Claude Sonnet 4 by Anthropic — balanced model with strong coding and reasoning abilities.',
    displayName: 'Claude Sonnet 4',
    enabled: false,
    family: 'claude',
    generation: 'claude-4',
    id: 'claude-sonnet-4',
    knowledgeCutoff: '2025-01',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 3.75, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-05-22',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description:
      'Claude Sonnet 4.5 by Anthropic — improved Sonnet with enhanced coding performance.',
    displayName: 'Claude Sonnet 4.5',
    enabled: false,
    family: 'claude',
    generation: 'claude-4.5',
    id: 'claude-sonnet-4-5',
    knowledgeCutoff: '2025-01',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 3.75, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-09-29',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description:
      'Claude Sonnet 4.6 by Anthropic — latest Sonnet with superior coding and tool use.',
    displayName: 'Claude Sonnet 4.6',
    enabled: false,
    family: 'claude',
    generation: 'claude-4.6',
    id: 'claude-sonnet-4-6',
    knowledgeCutoff: '2025-05',
    maxOutput: 32_000,
    organization: 'Anthropic',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 3.75, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-17',
    type: 'chat',
  },

  // ========== Google Gemini ==========
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_048_576,
    description: 'Gemini 3 Flash by Google — ultra-fast model with multimodal input support.',
    displayName: 'Gemini 3 Flash',
    enabled: false,
    family: 'gemini',
    generation: 'gemini-3',
    id: 'gemini-3-flash',
    maxOutput: 32_000,
    organization: 'Google',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.05, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-12-17',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_048_576,
    description: 'Gemini 3.1 Pro by Google — premium multimodal model with 1M context window.',
    displayName: 'Gemini 3.1 Pro',
    enabled: true,
    family: 'gemini',
    generation: 'gemini-3.1',
    id: 'gemini-3.1-pro',
    maxOutput: 32_000,
    organization: 'Google',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 12, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-19',
    type: 'chat',
  },

  // ========== Zhipu GLM ==========
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 204_800,
    description:
      'GLM-5 by Zhipu AI — high-performance coding model with strong reasoning abilities.',
    displayName: 'GLM-5',
    enabled: false,
    family: 'glm',
    generation: 'glm-5',
    id: 'glm-5',
    maxOutput: 32_000,
    organization: 'Zhipu',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-11',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 204_800,
    description: 'GLM-5.1 by Zhipu AI — latest generation coding model with enhanced reasoning.',
    displayName: 'GLM-5.1',
    enabled: true,
    family: 'glm',
    generation: 'glm-5.1',
    id: 'glm-5.1',
    maxOutput: 32_000,
    organization: 'Zhipu',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.26, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-04-07',
    type: 'chat',
  },

  // ========== OpenAI GPT ==========
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5 by OpenAI — flagship model with advanced reasoning and multimodal input.',
    displayName: 'GPT-5',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5',
    id: 'gpt-5',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.07, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.107, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-08-07',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5 Codex by OpenAI — coding-specialized variant with tool use support.',
    displayName: 'GPT-5 Codex',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5',
    id: 'gpt-5-codex',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.07, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.107, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-09-15',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5 Nano by OpenAI — lightweight and cost-efficient model.',
    displayName: 'GPT-5 Nano',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5',
    id: 'gpt-5-nano',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-08-07',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.1 by OpenAI — improved GPT-5 with better reasoning accuracy.',
    displayName: 'GPT-5.1',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.1',
    id: 'gpt-5.1',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.07, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.107, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-11-13',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.1 Codex by OpenAI — coding-focused variant with enhanced tool use.',
    displayName: 'GPT-5.1 Codex',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.1',
    id: 'gpt-5.1-codex',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.07, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.107, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-11-13',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.1 Codex Max by OpenAI — maximum capability Codex variant.',
    displayName: 'GPT-5.1 Codex Max',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.1',
    id: 'gpt-5.1-codex-max',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 10, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.125, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-11-13',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.1 Codex Mini by OpenAI — compact coding model with strong capabilities.',
    displayName: 'GPT-5.1 Codex Mini',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.1',
    id: 'gpt-5.1-codex-mini',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.025, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-11-13',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.2 by OpenAI — upgraded reasoning and multimodal processing.',
    displayName: 'GPT-5.2',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.2',
    id: 'gpt-5.2',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 14, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.175, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-12-11',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.2 Codex by OpenAI — coding-specialized with improved tool call accuracy.',
    displayName: 'GPT-5.2 Codex',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.2',
    id: 'gpt-5.2-codex',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 14, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.175, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-01-14',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.3 Codex by OpenAI — latest Codex with enhanced code understanding.',
    displayName: 'GPT-5.3 Codex',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.3',
    id: 'gpt-5.3-codex',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 14, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.175, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-24',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true },
    contextWindowTokens: 128_000,
    description: 'GPT-5.3 Codex Spark by OpenAI — compact coding model optimized for speed.',
    displayName: 'GPT-5.3 Codex Spark',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.3',
    id: 'gpt-5.3-codex-spark',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 1.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 14, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.175, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-12',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_050_000,
    description: 'GPT-5.4 by OpenAI — next-gen model with 1M+ context window and multimodal input.',
    displayName: 'GPT-5.4',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.4',
    id: 'gpt-5.4',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 2.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-03-05',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.4 Mini by OpenAI — efficient model balancing cost and performance.',
    displayName: 'GPT-5.4 Mini',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.4',
    id: 'gpt-5.4-mini',
    knowledgeCutoff: '2025-08',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.75, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.075, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-03-17',
    type: 'chat',
  },
  {
    abilities: { files: true, functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 400_000,
    description: 'GPT-5.4 Nano by OpenAI — ultra-lightweight model for high-throughput tasks.',
    displayName: 'GPT-5.4 Nano',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.4',
    id: 'gpt-5.4-nano',
    knowledgeCutoff: '2025-08',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.02, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-03-17',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 1_050_000,
    description: 'GPT-5.4 Pro by OpenAI — most capable model with maximum context and reasoning.',
    displayName: 'GPT-5.4 Pro',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.4',
    id: 'gpt-5.4-pro',
    knowledgeCutoff: '2025-08',
    maxOutput: 32_000,
    organization: 'OpenAI',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 30, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 180, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 30, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-03-05',
    type: 'chat',
  },

  // ========== Moonshot Kimi ==========
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 262_144,
    description:
      'Kimi K2.5 by Moonshot AI — advanced reasoning model with image and video input support.',
    displayName: 'Kimi K2.5',
    enabled: false,
    family: 'kimi',
    generation: 'kimi-k2.5',
    id: 'kimi-k2.5',
    maxOutput: 32_000,
    organization: 'Moonshot',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.6, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.08, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-01-27',
    type: 'chat',
  },

  // ========== MiniMax ==========
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 204_800,
    description: 'MiniMax M2.5 — efficient coding model with strong reasoning abilities.',
    displayName: 'MiniMax M2.5',
    enabled: false,
    family: 'minimax',
    generation: 'minimax-m2.5',
    id: 'minimax-m2.5',
    maxOutput: 32_000,
    organization: 'MiniMax',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.06, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-12',
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 204_800,
    description: 'MiniMax M2.5 Free — free tier coding model with full reasoning capabilities.',
    displayName: 'MiniMax M2.5 Free',
    enabled: true,
    family: 'minimax',
    generation: 'minimax-m2.5',
    id: 'minimax-m2.5-free',
    maxOutput: 32_000,
    organization: 'MiniMax',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-12',
    type: 'chat',
  },

  // ========== Nvidia Nemotron ==========
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 204_800,
    description:
      'Nemotron 3 Super Free by Nvidia — free tier reasoning model with strong coding support.',
    displayName: 'Nemotron 3 Super Free',
    enabled: true,
    id: 'nemotron-3-super-free',
    maxOutput: 32_000,
    organization: 'Nvidia',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-03-11',
    type: 'chat',
  },

  // ========== Alibaba Qwen ==========
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 262_144,
    description: 'Qwen3.5 Plus by Alibaba — cost-effective coding model with vision support.',
    displayName: 'Qwen3.5 Plus',
    enabled: false,
    family: 'qwen',
    generation: 'qwen3.5',
    id: 'qwen3.5-plus',
    maxOutput: 32_000,
    organization: 'Alibaba',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.02, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 0.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-02-16',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },
  {
    abilities: { functionCall: true, reasoning: true, vision: true },
    contextWindowTokens: 262_144,
    description:
      'Qwen3.6 Plus by Alibaba — latest Qwen coding model with enhanced reasoning and vision.',
    displayName: 'Qwen3.6 Plus',
    enabled: false,
    family: 'qwen',
    generation: 'qwen3.6',
    id: 'qwen3.6-plus',
    maxOutput: 32_000,
    organization: 'Alibaba',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0.05, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 0.625, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2026-04-02',
    settings: {
      extendParams: ['reasoningEffort'],
    },
    type: 'chat',
  },

  // ========== OpenCode (Own) ==========
  {
    abilities: { functionCall: true, reasoning: true },
    contextWindowTokens: 200_000,
    description:
      'Big Pickle by OpenCode — free open-weights model with strong coding capabilities.',
    displayName: 'Big Pickle',
    enabled: true,
    id: 'big-pickle',
    maxOutput: 32_000,
    organization: 'OpenCode',
    pricing: {
      currency: 'USD',
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheRead', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textInput_cacheWrite', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    releasedAt: '2025-10-17',
    type: 'chat',
  },
];

export default opencodeZenChatModels;
