/**
 * Write the local alint provider setup (`.alint/config.toml`, gitignored)
 * from environment variables so the API key never lands in the repo.
 *
 *   ALINT_API_KEY (or DEEPSEEK_API_KEY)   required
 *   ALINT_PROVIDER_ENDPOINT               default https://api.deepseek.com/v1
 *   ALINT_MODEL                           default deepseek-flash
 *
 * `thinking` is disabled on the model: alint forces a tool call for
 * structured output and DeepSeek V4 rejects that while reasoning is on.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

const apiKey = process.env.ALINT_API_KEY ?? process.env.DEEPSEEK_API_KEY;
const endpoint = process.env.ALINT_PROVIDER_ENDPOINT ?? 'https://api.deepseek.com/v1';
const model = process.env.ALINT_MODEL ?? 'deepseek-flash';

if (!apiKey) {
  console.error('✗ set ALINT_API_KEY (or DEEPSEEK_API_KEY) before running alint:setup');
  process.exit(2);
}

const providerId = new URL(endpoint).hostname;

const toml = `# Generated by \`bun run alint:setup\`; gitignored because it holds the key.
version = 1

[[providers]]
id = "${providerId}"
type = "openai-compatible"
endpoint = "${endpoint}"

[providers.headers]
Authorization = "Bearer ${apiKey}"

[[providers.models]]
id = "${model}"
name = "${model}"
size = "small"
aliases = [ "default" ]
capabilities = [ "tool-call" ]

[providers.models.default_params]
thinking = { type = "disabled" }
`;

const target = path.join(rootDir, '.alint/config.toml');
await mkdir(path.dirname(target), { recursive: true });
await writeFile(target, toml, { mode: 0o600 });
console.info(`✓ wrote ${path.relative(rootDir, target)} (${providerId} / ${model})`);
console.info('  next: bun run alint plugin install && bun run check --alint');
