import { type LucideIcon } from 'lucide-react';

// ======== Page Types ======== //

/**
 * All supported page types for recently viewed
 */
export type PageType =
  | 'agent'
  | 'agent-topic'
  | 'group'
  | 'group-topic'
  | 'page'
  | 'settings'
  | 'community'
  | 'resource'
  | 'memory'
  | 'image'
  | 'home';

// ======== Page Params ======== //

export interface AgentParams {
  agentId: string;
}

export interface AgentTopicParams {
  agentId: string;
  topicId: string;
}

export interface GroupParams {
  groupId: string;
}

export interface GroupTopicParams {
  groupId: string;
  topicId: string;
}

export interface PageParams {
  pageId: string;
}

export interface SettingsParams {
  section?: string;
}

export interface CommunityParams {
  section?: string;
}

export interface ResourceParams {
  section?: string;
}

export interface MemoryParams {
  section?: string;
}

export interface ImageParams {
  section?: string;
}

export interface HomeParams {}

/**
 * Type-safe params mapping for each page type
 */
export interface PageParamsMap {
  'agent': AgentParams;
  'agent-topic': AgentTopicParams;
  'community': CommunityParams;
  'group': GroupParams;
  'group-topic': GroupTopicParams;
  'home': HomeParams;
  'image': ImageParams;
  'memory': MemoryParams;
  'page': PageParams;
  'resource': ResourceParams;
  'settings': SettingsParams;
}

// ======== Cached Display Data ======== //

/**
 * Cached display data stored with page reference
 * Used as fallback when store data is not available
 */
export interface CachedPageData {
  /**
   * Avatar URL
   */
  avatar?: string;
  /**
   * Background color for avatar
   */
  backgroundColor?: string;
  /**
   * Display title
   */
  title: string;
}

// ======== Page Reference (Storage) ======== //

/**
 * Structured page reference for storage
 * This replaces the old PageEntry type
 */
export interface PageReference<T extends PageType = PageType> {
  /**
   * Cached display data for when store data is unavailable
   * This ensures pinned pages can display even after app restart
   */
  cached?: CachedPageData;
  /**
   * Unique identifier combining type and params
   * e.g., "agent:abc123" or "agent-topic:abc123:topic456"
   */
  id: string;
  /**
   * Timestamp of last visit
   */
  lastVisited: number;
  /**
   * Type-specific parameters
   */
  params: PageParamsMap[T];
  /**
   * Page type
   */
  type: T;
  /**
   * Visit count for sorting/analytics
   */
  visitCount?: number;
}

// ======== Resolved Page Data (Display) ======== //

/**
 * Resolved page data ready for rendering
 * Contains all display information generated by plugins
 */
export interface ResolvedPageData {
  /**
   * Avatar URL for agent/group pages
   */
  avatar?: string;
  /**
   * Background color for avatar
   */
  backgroundColor?: string;
  /**
   * Whether the underlying data exists
   * Pages with exists=false should be filtered out
   */
  exists: boolean;
  /**
   * Icon to display
   */
  icon?: LucideIcon;
  /**
   * Original reference for navigation and pin/unpin
   */
  reference: PageReference;
  /**
   * Display title
   */
  title: string;
  /**
   * Generated URL for navigation
   */
  url: string;
}
